### ISSUE TITLE
Setup continuous integration.

### ISSUE THREAD

**Issue by mtwilliams** [mtwilliams/bamboo-sendgrid#2]
Broken down:
- [x] Building on TravisCI.
- [x] All tests passing on TravisCI.
- [ ] All tests pass against SendGrid.

On the third point, I'll setup a free plan with SendGrid and use [sink addresses.](https://support.sendgrid.com/hc/en-us/articles/201995663-Safely-Test-Your-Sending-Speed) I may be able to convince them to provide a higher rate-limit. (Or we should only perform tests against SendGrid prior to release.)
